const fieldsMapping = {
    paperTitle: 'Paper Title',
    organizer : 'Organizer',
    place : 'Place',
    isbn : 'ISBN',
    sPageNo :  'Start Page Number',
    ePageNo : 'End Page Number',
    epageno: 'End Page Number',
    spageno :  'Start Page Number',
    startDate  : 'Start Date',
    endDate : 'End Date',
    pubDate : 'Publishing Date',
    publisher : 'Publisher',
    finType : 'Financing Type',
    regionType : 'Region Type',
    authors : 'Authors',
    remarks: 'Remarks',
    title : 'Title',
    pubCategory: 'Publication Category',
    jname: "Journal Name",
    volumeno: "Volume Number",
    issueno: "Issue Number",
    issn : "ISSN",
    webUrl: "Web URL",
    indexedBy: "Indexed By",
    isUgcApproved: "UGC Approved",
    isHardCopy: "Hard Copy",
    activityName: "Activity Name",
    awardName: "Award Name",
    awardingInstitution: "Awarding Institution",
    awardDate: "Award Date",
    isPublished: "Published",
}

export default fieldsMapping;
